name: Reusable workflow
on: 
    workflow_call:
        inputs:
            artifact-file:
                description: Our artifact file
                required: 'false'
                default: my-artifact
                type: string
jobs:
    deploy:
        runs-on: ubuntu-latest 
        env:
           my_message: "hello world"
        steps:
           - name: Get artifacts
             uses: actions/download-artifact@v4
             with:
              name: ${{ inputs.artifact-file }}
           - name: list artifact file
             run: ls     
           - name: deploy web artifact
             run: echo "Deploying web app artifact..."   
           - name: see output
             run: echo ${{ needs.build.outputs.my_output }}
           - name: Get information
             run: echo ${{ env.my_message }}
