name: Reusable workflow
on: 
    workflow_call:
        inputs:
            artifact-file:
                description: Our artifact file
                required: true
                default: artifact
                type: string
        outputs:
            my-output:
                description: testing outputs in reusable workflows
                value: ${{ jobs.deploy.outputs.job-outputs }}
jobs:
    deploy:
        runs-on: ubuntu-latest 
        outputs:
            job-output: ${{ steps.willy-id.outputs.test-output }}
        env:
           my_message: "hello world"
        steps:
           - name: Get artifacts
             uses: actions/download-artifact@v4
             with:
              name: ${{ inputs.artifact-file }}
           - name: list artifact file
             run: ls     
           - name: deploy web artifact
             run: echo "Deploying web app artifact..."   
           - name: see output
             run: echo ${{ needs.build.outputs.my_output }}
           - name: Get information
             run: echo ${{ env.my_message }}
           - name: Get Output
             id: willy-id   
             run: echo "test-output='hello world'" >> $GITHUB_OUTPUT   
